language: node_js

node_js:
  - '10'

env:
  global:
    - workerCount=3
    - timeout=600000
    - REACT_APP_TRAVIS=true

matrix:
  fast_finish: true

dist: trusty
cache: yarn

install:
  - yarn install

branches:
  only:
    - master

script:
  - yarn lint
  - npm run build