language: node_js

node_js:
  - '10'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

dist: trusty
cache: yarn

install:
  - yarn install

branches:
  only:
    - master

script:
  - yarn lint
  - npm run build