language: node_js

node_js:
  - 'node'
  - '10'
  - '8'

env:
  - workerCount=3 timeout=600000

matrix:
  fast_finish: true

dist: trusty
sudo: false
cache: yarn

install:
  - yarn install

branches:
  only:
    - master
    - develop

script:
  - yarn lint