// tslint:disable
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    title: string;
    /**
     * 
     * @type {Array<Category>}
     * @memberof Article
     */
    categories: Array<Category>;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    createdDate: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    updatedDate: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    imageName: string;
    /**
     * 
     * @type {boolean}
     * @memberof Article
     */
    _private: boolean;
}
/**
 * 
 * @export
 * @interface ArticleReq
 */
export interface ArticleReq {
    /**
     * 
     * @type {string}
     * @memberof ArticleReq
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleReq
     */
    title: string;
    /**
     * 
     * @type {Array<ArticleReqCategories>}
     * @memberof ArticleReq
     */
    categories: Array<ArticleReqCategories>;
    /**
     * 
     * @type {string}
     * @memberof ArticleReq
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleReq
     */
    imageName: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleReq
     */
    _private: boolean;
}
/**
 * 
 * @export
 * @interface ArticleReqCategories
 */
export interface ArticleReqCategories {
    /**
     * 
     * @type {string}
     * @memberof ArticleReqCategories
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleReqCategories
     */
    name: string;
}
/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    articleNum: number;
}
/**
 * 
 * @export
 * @interface Draft
 */
export interface Draft {
    /**
     * 
     * @type {string}
     * @memberof Draft
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Draft
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Draft
     */
    categories: string;
    /**
     * 
     * @type {string}
     * @memberof Draft
     */
    updatedDate: string;
    /**
     * 
     * @type {string}
     * @memberof Draft
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Draft
     */
    imageName: string;
}
/**
 * 
 * @export
 * @interface DraftReq
 */
export interface DraftReq {
    /**
     * 
     * @type {string}
     * @memberof DraftReq
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DraftReq
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof DraftReq
     */
    categories: string;
    /**
     * 
     * @type {string}
     * @memberof DraftReq
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof DraftReq
     */
    imageName: string;
}
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {ArticleReq}
     * @memberof InlineObject
     */
    article: ArticleReq;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    draftId?: string;
}
/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * 
     * @type {DraftReq}
     * @memberof InlineObject1
     */
    draft: DraftReq;
}
/**
 * 
 * @export
 * @interface InlineObject2
 */
export interface InlineObject2 {
    /**
     * 
     * @type {any}
     * @memberof InlineObject2
     */
    images?: any;
}
/**
 * 
 * @export
 * @interface InlineObject3
 */
export interface InlineObject3 {
    /**
     * 
     * @type {ArticleReq}
     * @memberof InlineObject3
     */
    article: ArticleReq;
}
/**
 * 
 * @export
 * @interface InlineObject4
 */
export interface InlineObject4 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject4
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof InlineObject4
     */
    _private: boolean;
}
/**
 * 
 * @export
 * @interface InlineObject5
 */
export interface InlineObject5 {
    /**
     * 
     * @type {DraftReq}
     * @memberof InlineObject5
     */
    draft: DraftReq;
}
/**
 * 
 * @export
 * @interface InlineObject6
 */
export interface InlineObject6 {
    /**
     * 
     * @type {string}
     * @memberof InlineObject6
     */
    id?: string;
}
/**
 * 
 * @export
 * @interface InlineObject7
 */
export interface InlineObject7 {
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineObject7
     */
    imageNames?: Array<string>;
}
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * 
     * @type {Array<Article>}
     * @memberof InlineResponse200
     */
    articles: Array<Article>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    count: number;
}
/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {Article}
     * @memberof InlineResponse2001
     */
    article: Article;
    /**
     * 
     * @type {Article}
     * @memberof InlineResponse2001
     */
    nextArticle: Article;
    /**
     * 
     * @type {Article}
     * @memberof InlineResponse2001
     */
    prevArticle: Article;
}
/**
 * 
 * @export
 * @interface InlineResponse2002
 */
export interface InlineResponse2002 {
    /**
     * 
     * @type {Array<Category>}
     * @memberof InlineResponse2002
     */
    categories: Array<Category>;
}
/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * 
     * @type {Article}
     * @memberof InlineResponse2003
     */
    article: Article;
}
/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 
     * @type {Draft}
     * @memberof InlineResponse2004
     */
    draft: Draft;
}
/**
 * 
 * @export
 * @interface InlineResponse2005
 */
export interface InlineResponse2005 {
    /**
     * 
     * @type {Array<Draft>}
     * @memberof InlineResponse2005
     */
    drafts: Array<Draft>;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse2005
     */
    count: number;
}
/**
 * 
 * @export
 * @interface InlineResponse2006
 */
export interface InlineResponse2006 {
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse2006
     */
    images: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof InlineResponse2006
     */
    next: boolean;
}
/**
 * 
 * @export
 * @interface InlineResponse2007
 */
export interface InlineResponse2007 {
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse2007
     */
    imageHash: string;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Return an articles by id.
         * @param {string} id Article id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleIdGet: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiFindArticleIdGet.');
            }
            const localVarPath = `/api/find/article/id`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return articles list by category.
         * @param {Array<string>} categoryId Category name.
         * @param {number} p Page number.
         * @param {number} num number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleListCategoryGet: async (categoryId: Array<string>, p: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'categoryId' is not null or undefined
            if (categoryId === null || categoryId === undefined) {
                throw new RequiredError('categoryId','Required parameter categoryId was null or undefined when calling apiFindArticleListCategoryGet.');
            }
            // verify required parameter 'p' is not null or undefined
            if (p === null || p === undefined) {
                throw new RequiredError('p','Required parameter p was null or undefined when calling apiFindArticleListCategoryGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling apiFindArticleListCategoryGet.');
            }
            const localVarPath = `/api/find/article/list/category`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (categoryId) {
                localVarQueryParameter['categoryId'] = categoryId;
            }

            if (p !== undefined) {
                localVarQueryParameter['p'] = p;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return articles list.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleListGet: async (p: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'p' is not null or undefined
            if (p === null || p === undefined) {
                throw new RequiredError('p','Required parameter p was null or undefined when calling apiFindArticleListGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling apiFindArticleListGet.');
            }
            const localVarPath = `/api/find/article/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (p !== undefined) {
                localVarQueryParameter['p'] = p;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return articles list by title.
         * @param {string} title Article title.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleListTitleGet: async (title: string, p: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'title' is not null or undefined
            if (title === null || title === undefined) {
                throw new RequiredError('title','Required parameter title was null or undefined when calling apiFindArticleListTitleGet.');
            }
            // verify required parameter 'p' is not null or undefined
            if (p === null || p === undefined) {
                throw new RequiredError('p','Required parameter p was null or undefined when calling apiFindArticleListTitleGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling apiFindArticleListTitleGet.');
            }
            const localVarPath = `/api/find/article/list/title`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (title !== undefined) {
                localVarQueryParameter['title'] = title;
            }

            if (p !== undefined) {
                localVarQueryParameter['p'] = p;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return categories list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindCategoryListGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/find/category/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete draft.
         * @param {InlineObject6} inlineObject6 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateDeleteDraftDelete: async (inlineObject6: InlineObject6, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject6' is not null or undefined
            if (inlineObject6 === null || inlineObject6 === undefined) {
                throw new RequiredError('inlineObject6','Required parameter inlineObject6 was null or undefined when calling apiPrivateDeleteDraftDelete.');
            }
            const localVarPath = `/api/private/delete/draft`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject6 !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject6 !== undefined ? inlineObject6 : {}) : (inlineObject6 || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete images.
         * @param {InlineObject7} inlineObject7 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateDeleteImageDelete: async (inlineObject7: InlineObject7, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject7' is not null or undefined
            if (inlineObject7 === null || inlineObject7 === undefined) {
                throw new RequiredError('inlineObject7','Required parameter inlineObject7 was null or undefined when calling apiPrivateDeleteImageDelete.');
            }
            const localVarPath = `/api/private/delete/image`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject7 !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject7 !== undefined ? inlineObject7 : {}) : (inlineObject7 || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return an article whose id is selected
         * @param {string} id Article id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindArticleIdGet: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiPrivateFindArticleIdGet.');
            }
            const localVarPath = `/api/private/find/article/id`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return all articles list.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindArticleListGet: async (p: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'p' is not null or undefined
            if (p === null || p === undefined) {
                throw new RequiredError('p','Required parameter p was null or undefined when calling apiPrivateFindArticleListGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling apiPrivateFindArticleListGet.');
            }
            const localVarPath = `/api/private/find/article/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (p !== undefined) {
                localVarQueryParameter['p'] = p;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return a draft whose id is selected.
         * @param {string} id Draft id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindDraftIdGet: async (id: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiPrivateFindDraftIdGet.');
            }
            const localVarPath = `/api/private/find/draft/id`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return all drafts list.
         * @param {number} p Page number.
         * @param {number} num Number of drafts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindDraftListGet: async (p: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'p' is not null or undefined
            if (p === null || p === undefined) {
                throw new RequiredError('p','Required parameter p was null or undefined when calling apiPrivateFindDraftListGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling apiPrivateFindDraftListGet.');
            }
            const localVarPath = `/api/private/find/draft/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (p !== undefined) {
                localVarQueryParameter['p'] = p;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Return images list.
         * @param {number} p Page number.
         * @param {number} num Number of images.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindImageListGet: async (p: number, num: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'p' is not null or undefined
            if (p === null || p === undefined) {
                throw new RequiredError('p','Required parameter p was null or undefined when calling apiPrivateFindImageListGet.');
            }
            // verify required parameter 'num' is not null or undefined
            if (num === null || num === undefined) {
                throw new RequiredError('num','Required parameter num was null or undefined when calling apiPrivateFindImageListGet.');
            }
            const localVarPath = `/api/private/find/image/list`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (p !== undefined) {
                localVarQueryParameter['p'] = p;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register new article.
         * @param {InlineObject} inlineObject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateRegisterArticlePost: async (inlineObject: InlineObject, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject' is not null or undefined
            if (inlineObject === null || inlineObject === undefined) {
                throw new RequiredError('inlineObject','Required parameter inlineObject was null or undefined when calling apiPrivateRegisterArticlePost.');
            }
            const localVarPath = `/api/private/register/article`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject !== undefined ? inlineObject : {}) : (inlineObject || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register new draft.
         * @param {InlineObject1} inlineObject1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateRegisterDraftPost: async (inlineObject1: InlineObject1, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject1' is not null or undefined
            if (inlineObject1 === null || inlineObject1 === undefined) {
                throw new RequiredError('inlineObject1','Required parameter inlineObject1 was null or undefined when calling apiPrivateRegisterDraftPost.');
            }
            const localVarPath = `/api/private/register/draft`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject1 !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject1 !== undefined ? inlineObject1 : {}) : (inlineObject1 || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register new image.
         * @param {any} [images] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateRegisterImagePost: async (images?: any, options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/private/register/image`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new FormData();

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


            if (images !== undefined) { 
                localVarFormParams.append('images', images as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update article\'s private property.
         * @param {InlineObject4} inlineObject4 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateUpdateArticlePrivatePut: async (inlineObject4: InlineObject4, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject4' is not null or undefined
            if (inlineObject4 === null || inlineObject4 === undefined) {
                throw new RequiredError('inlineObject4','Required parameter inlineObject4 was null or undefined when calling apiPrivateUpdateArticlePrivatePut.');
            }
            const localVarPath = `/api/private/update/article/private`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject4 !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject4 !== undefined ? inlineObject4 : {}) : (inlineObject4 || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update article.
         * @param {InlineObject3} inlineObject3 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateUpdateArticlePut: async (inlineObject3: InlineObject3, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject3' is not null or undefined
            if (inlineObject3 === null || inlineObject3 === undefined) {
                throw new RequiredError('inlineObject3','Required parameter inlineObject3 was null or undefined when calling apiPrivateUpdateArticlePut.');
            }
            const localVarPath = `/api/private/update/article`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject3 !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject3 !== undefined ? inlineObject3 : {}) : (inlineObject3 || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update draft.
         * @param {InlineObject5} inlineObject5 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateUpdateDraftPut: async (inlineObject5: InlineObject5, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'inlineObject5' is not null or undefined
            if (inlineObject5 === null || inlineObject5 === undefined) {
                throw new RequiredError('inlineObject5','Required parameter inlineObject5 was null or undefined when calling apiPrivateUpdateDraftPut.');
            }
            const localVarPath = `/api/private/update/draft`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof inlineObject5 !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(inlineObject5 !== undefined ? inlineObject5 : {}) : (inlineObject5 || "");

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVerifyTokenPost: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/verify/token`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Return an articles by id.
         * @param {string} id Article id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiFindArticleIdGet(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2001>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiFindArticleIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return articles list by category.
         * @param {Array<string>} categoryId Category name.
         * @param {number} p Page number.
         * @param {number} num number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiFindArticleListCategoryGet(categoryId: Array<string>, p: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiFindArticleListCategoryGet(categoryId, p, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return articles list.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiFindArticleListGet(p: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiFindArticleListGet(p, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return articles list by title.
         * @param {string} title Article title.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiFindArticleListTitleGet(title: string, p: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiFindArticleListTitleGet(title, p, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return categories list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiFindCategoryListGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2002>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiFindCategoryListGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete draft.
         * @param {InlineObject6} inlineObject6 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateDeleteDraftDelete(inlineObject6: InlineObject6, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateDeleteDraftDelete(inlineObject6, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Delete images.
         * @param {InlineObject7} inlineObject7 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateDeleteImageDelete(inlineObject7: InlineObject7, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateDeleteImageDelete(inlineObject7, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return an article whose id is selected
         * @param {string} id Article id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateFindArticleIdGet(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2003>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateFindArticleIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return all articles list.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateFindArticleListGet(p: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse200>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateFindArticleListGet(p, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return a draft whose id is selected.
         * @param {string} id Draft id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateFindDraftIdGet(id: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2004>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateFindDraftIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return all drafts list.
         * @param {number} p Page number.
         * @param {number} num Number of drafts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateFindDraftListGet(p: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2005>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateFindDraftListGet(p, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Return images list.
         * @param {number} p Page number.
         * @param {number} num Number of images.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateFindImageListGet(p: number, num: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2006>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateFindImageListGet(p, num, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Register new article.
         * @param {InlineObject} inlineObject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateRegisterArticlePost(inlineObject: InlineObject, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateRegisterArticlePost(inlineObject, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Register new draft.
         * @param {InlineObject1} inlineObject1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateRegisterDraftPost(inlineObject1: InlineObject1, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InlineResponse2007>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateRegisterDraftPost(inlineObject1, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Register new image.
         * @param {any} [images] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateRegisterImagePost(images?: any, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateRegisterImagePost(images, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update article\'s private property.
         * @param {InlineObject4} inlineObject4 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateUpdateArticlePrivatePut(inlineObject4: InlineObject4, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateUpdateArticlePrivatePut(inlineObject4, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update article.
         * @param {InlineObject3} inlineObject3 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateUpdateArticlePut(inlineObject3: InlineObject3, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateUpdateArticlePut(inlineObject3, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Update draft.
         * @param {InlineObject5} inlineObject5 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiPrivateUpdateDraftPut(inlineObject5: InlineObject5, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiPrivateUpdateDraftPut(inlineObject5, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Verify token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiVerifyTokenPost(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await DefaultApiAxiosParamCreator(configuration).apiVerifyTokenPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Return an articles by id.
         * @param {string} id Article id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleIdGet(id: string, options?: any): AxiosPromise<InlineResponse2001> {
            return DefaultApiFp(configuration).apiFindArticleIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return articles list by category.
         * @param {Array<string>} categoryId Category name.
         * @param {number} p Page number.
         * @param {number} num number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleListCategoryGet(categoryId: Array<string>, p: number, num: number, options?: any): AxiosPromise<InlineResponse200> {
            return DefaultApiFp(configuration).apiFindArticleListCategoryGet(categoryId, p, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return articles list.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleListGet(p: number, num: number, options?: any): AxiosPromise<InlineResponse200> {
            return DefaultApiFp(configuration).apiFindArticleListGet(p, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return articles list by title.
         * @param {string} title Article title.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindArticleListTitleGet(title: string, p: number, num: number, options?: any): AxiosPromise<InlineResponse200> {
            return DefaultApiFp(configuration).apiFindArticleListTitleGet(title, p, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return categories list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiFindCategoryListGet(options?: any): AxiosPromise<InlineResponse2002> {
            return DefaultApiFp(configuration).apiFindCategoryListGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete draft.
         * @param {InlineObject6} inlineObject6 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateDeleteDraftDelete(inlineObject6: InlineObject6, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiPrivateDeleteDraftDelete(inlineObject6, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete images.
         * @param {InlineObject7} inlineObject7 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateDeleteImageDelete(inlineObject7: InlineObject7, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiPrivateDeleteImageDelete(inlineObject7, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return an article whose id is selected
         * @param {string} id Article id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindArticleIdGet(id: string, options?: any): AxiosPromise<InlineResponse2003> {
            return DefaultApiFp(configuration).apiPrivateFindArticleIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return all articles list.
         * @param {number} p Page number.
         * @param {number} num Number of articles.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindArticleListGet(p: number, num: number, options?: any): AxiosPromise<InlineResponse200> {
            return DefaultApiFp(configuration).apiPrivateFindArticleListGet(p, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return a draft whose id is selected.
         * @param {string} id Draft id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindDraftIdGet(id: string, options?: any): AxiosPromise<InlineResponse2004> {
            return DefaultApiFp(configuration).apiPrivateFindDraftIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return all drafts list.
         * @param {number} p Page number.
         * @param {number} num Number of drafts.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindDraftListGet(p: number, num: number, options?: any): AxiosPromise<InlineResponse2005> {
            return DefaultApiFp(configuration).apiPrivateFindDraftListGet(p, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Return images list.
         * @param {number} p Page number.
         * @param {number} num Number of images.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateFindImageListGet(p: number, num: number, options?: any): AxiosPromise<InlineResponse2006> {
            return DefaultApiFp(configuration).apiPrivateFindImageListGet(p, num, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register new article.
         * @param {InlineObject} inlineObject 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateRegisterArticlePost(inlineObject: InlineObject, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiPrivateRegisterArticlePost(inlineObject, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register new draft.
         * @param {InlineObject1} inlineObject1 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateRegisterDraftPost(inlineObject1: InlineObject1, options?: any): AxiosPromise<InlineResponse2007> {
            return DefaultApiFp(configuration).apiPrivateRegisterDraftPost(inlineObject1, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register new image.
         * @param {any} [images] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateRegisterImagePost(images?: any, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiPrivateRegisterImagePost(images, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update article\'s private property.
         * @param {InlineObject4} inlineObject4 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateUpdateArticlePrivatePut(inlineObject4: InlineObject4, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiPrivateUpdateArticlePrivatePut(inlineObject4, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update article.
         * @param {InlineObject3} inlineObject3 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateUpdateArticlePut(inlineObject3: InlineObject3, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiPrivateUpdateArticlePut(inlineObject3, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update draft.
         * @param {InlineObject5} inlineObject5 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiPrivateUpdateDraftPut(inlineObject5: InlineObject5, options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiPrivateUpdateDraftPut(inlineObject5, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify token.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiVerifyTokenPost(options?: any): AxiosPromise<void> {
            return DefaultApiFp(configuration).apiVerifyTokenPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Return an articles by id.
     * @param {string} id Article id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiFindArticleIdGet(id: string, options?: any) {
        return DefaultApiFp(this.configuration).apiFindArticleIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return articles list by category.
     * @param {Array<string>} categoryId Category name.
     * @param {number} p Page number.
     * @param {number} num number of articles.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiFindArticleListCategoryGet(categoryId: Array<string>, p: number, num: number, options?: any) {
        return DefaultApiFp(this.configuration).apiFindArticleListCategoryGet(categoryId, p, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return articles list.
     * @param {number} p Page number.
     * @param {number} num Number of articles.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiFindArticleListGet(p: number, num: number, options?: any) {
        return DefaultApiFp(this.configuration).apiFindArticleListGet(p, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return articles list by title.
     * @param {string} title Article title.
     * @param {number} p Page number.
     * @param {number} num Number of articles.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiFindArticleListTitleGet(title: string, p: number, num: number, options?: any) {
        return DefaultApiFp(this.configuration).apiFindArticleListTitleGet(title, p, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return categories list.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiFindCategoryListGet(options?: any) {
        return DefaultApiFp(this.configuration).apiFindCategoryListGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete draft.
     * @param {InlineObject6} inlineObject6 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateDeleteDraftDelete(inlineObject6: InlineObject6, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateDeleteDraftDelete(inlineObject6, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete images.
     * @param {InlineObject7} inlineObject7 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateDeleteImageDelete(inlineObject7: InlineObject7, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateDeleteImageDelete(inlineObject7, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return an article whose id is selected
     * @param {string} id Article id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateFindArticleIdGet(id: string, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateFindArticleIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return all articles list.
     * @param {number} p Page number.
     * @param {number} num Number of articles.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateFindArticleListGet(p: number, num: number, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateFindArticleListGet(p, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return a draft whose id is selected.
     * @param {string} id Draft id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateFindDraftIdGet(id: string, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateFindDraftIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return all drafts list.
     * @param {number} p Page number.
     * @param {number} num Number of drafts.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateFindDraftListGet(p: number, num: number, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateFindDraftListGet(p, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Return images list.
     * @param {number} p Page number.
     * @param {number} num Number of images.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateFindImageListGet(p: number, num: number, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateFindImageListGet(p, num, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register new article.
     * @param {InlineObject} inlineObject 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateRegisterArticlePost(inlineObject: InlineObject, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateRegisterArticlePost(inlineObject, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register new draft.
     * @param {InlineObject1} inlineObject1 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateRegisterDraftPost(inlineObject1: InlineObject1, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateRegisterDraftPost(inlineObject1, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register new image.
     * @param {any} [images] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateRegisterImagePost(images?: any, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateRegisterImagePost(images, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update article\'s private property.
     * @param {InlineObject4} inlineObject4 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateUpdateArticlePrivatePut(inlineObject4: InlineObject4, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateUpdateArticlePrivatePut(inlineObject4, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update article.
     * @param {InlineObject3} inlineObject3 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateUpdateArticlePut(inlineObject3: InlineObject3, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateUpdateArticlePut(inlineObject3, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update draft.
     * @param {InlineObject5} inlineObject5 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiPrivateUpdateDraftPut(inlineObject5: InlineObject5, options?: any) {
        return DefaultApiFp(this.configuration).apiPrivateUpdateDraftPut(inlineObject5, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify token.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public apiVerifyTokenPost(options?: any) {
        return DefaultApiFp(this.configuration).apiVerifyTokenPost(options).then((request) => request(this.axios, this.basePath));
    }

}


