/* tslint:disable */
/* eslint-disable */
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Tag,
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
} from './';

/**
 * 
 * @export
 * @interface Article
 */
export interface Article {
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    title: string;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof Article
     */
    tags: Array<Tag>;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof Article
     */
    imageUrl: string;
    /**
     * 
     * @type {number}
     * @memberof Article
     */
    status: number;
}

export function ArticleFromJSON(json: any): Article {
    return ArticleFromJSONTyped(json, false);
}

export function ArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Article {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'tags': ((json['tags'] as Array<any>).map(TagFromJSON)),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'content': json['content'],
        'imageUrl': json['image_url'],
        'status': json['status'],
    };
}

export function ArticleToJSON(value?: Article | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'tags': ((value.tags as Array<any>).map(TagToJSON)),
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'content': value.content,
        'image_url': value.imageUrl,
        'status': value.status,
    };
}


