/* tslint:disable */
/* eslint-disable */
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteArticleRequestBody
 */
export interface DeleteArticleRequestBody {
    /**
     * 
     * @type {string}
     * @memberof DeleteArticleRequestBody
     */
    id: string;
}

export function DeleteArticleRequestBodyFromJSON(json: any): DeleteArticleRequestBody {
    return DeleteArticleRequestBodyFromJSONTyped(json, false);
}

export function DeleteArticleRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteArticleRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DeleteArticleRequestBodyToJSON(value?: DeleteArticleRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


