/* tslint:disable */
/* eslint-disable */
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteImagesRequestBody
 */
export interface DeleteImagesRequestBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof DeleteImagesRequestBody
     */
    imageUrls: Array<string>;
}

export function DeleteImagesRequestBodyFromJSON(json: any): DeleteImagesRequestBody {
    return DeleteImagesRequestBodyFromJSONTyped(json, false);
}

export function DeleteImagesRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteImagesRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageUrls': json['image_urls'],
    };
}

export function DeleteImagesRequestBodyToJSON(value?: DeleteImagesRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_urls': value.imageUrls,
    };
}


