/* tslint:disable */
/* eslint-disable */
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Pagenation,
    PagenationFromJSON,
    PagenationFromJSONTyped,
    PagenationToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {
    /**
     * 
     * @type {Array<string>}
     * @memberof InlineResponse2003
     */
    imageUrls: Array<string>;
    /**
     * 
     * @type {Pagenation}
     * @memberof InlineResponse2003
     */
    pagenation: Pagenation;
}

export function InlineResponse2003FromJSON(json: any): InlineResponse2003 {
    return InlineResponse2003FromJSONTyped(json, false);
}

export function InlineResponse2003FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2003 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageUrls': json['image_urls'],
        'pagenation': PagenationFromJSON(json['pagenation']),
    };
}

export function InlineResponse2003ToJSON(value?: InlineResponse2003 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_urls': value.imageUrls,
        'pagenation': PagenationToJSON(value.pagenation),
    };
}


