/* tslint:disable */
/* eslint-disable */
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Pagenation
 */
export interface Pagenation {
    /**
     * 
     * @type {boolean}
     * @memberof Pagenation
     */
    next: boolean;
    /**
     * 
     * @type {number}
     * @memberof Pagenation
     */
    current: number;
    /**
     * 
     * @type {boolean}
     * @memberof Pagenation
     */
    prev: boolean;
}

export function PagenationFromJSON(json: any): Pagenation {
    return PagenationFromJSONTyped(json, false);
}

export function PagenationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pagenation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'next': json['next'],
        'current': json['current'],
        'prev': json['prev'],
    };
}

export function PagenationToJSON(value?: Pagenation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'next': value.next,
        'current': value.current,
        'prev': value.prev,
    };
}


