/* tslint:disable */
/* eslint-disable */
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PostTag,
    PostTagFromJSON,
    PostTagFromJSONTyped,
    PostTagToJSON,
} from './';

/**
 * 
 * @export
 * @interface PostArticle
 */
export interface PostArticle {
    /**
     * 
     * @type {string}
     * @memberof PostArticle
     */
    title: string;
    /**
     * 
     * @type {Array<PostTag>}
     * @memberof PostArticle
     */
    tags: Array<PostTag>;
    /**
     * 
     * @type {string}
     * @memberof PostArticle
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof PostArticle
     */
    imageUrl: string;
}

export function PostArticleFromJSON(json: any): PostArticle {
    return PostArticleFromJSONTyped(json, false);
}

export function PostArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostArticle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'tags': ((json['tags'] as Array<any>).map(PostTagFromJSON)),
        'content': json['content'],
        'imageUrl': json['image_url'],
    };
}

export function PostArticleToJSON(value?: PostArticle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'tags': ((value.tags as Array<any>).map(PostTagToJSON)),
        'content': value.content,
        'image_url': value.imageUrl,
    };
}


