/* tslint:disable */
/* eslint-disable */
/**
 * argus
 * My blog
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateArticleStatusRequestBody
 */
export interface UpdateArticleStatusRequestBody {
    /**
     * 
     * @type {string}
     * @memberof UpdateArticleStatusRequestBody
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateArticleStatusRequestBody
     */
    status: number;
}

export function UpdateArticleStatusRequestBodyFromJSON(json: any): UpdateArticleStatusRequestBody {
    return UpdateArticleStatusRequestBodyFromJSONTyped(json, false);
}

export function UpdateArticleStatusRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateArticleStatusRequestBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
    };
}

export function UpdateArticleStatusRequestBodyToJSON(value?: UpdateArticleStatusRequestBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': value.status,
    };
}


